version: "3"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecomdb
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      POSTGRES_URI: postgres://postgres:password@db:5432/ecomdb
    ports:
      - "9000:9000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3005:3000"
    depends_on:
      - backend

